baseURL = "https://www.cognitivereflex.com/"
languageCode = "en-us"
title = "Cognitive Reflex"
theme="tailwinds-theme"
staticDir = ["static",]

author = "FI Diego"
copyright = "Copyright © 2019, FI Diego, all rights reserved."

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

[params]
    name = "Cognitive Reflex"
    description = "Bit Jockey | Code Mechanic | Purveyor of fine APIs"

    github_user = "fidiego"
    github_repo = "https://github.com/fidiego/www.cognitivereflex.com"

    favicon = "favicon.ico"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
