[build]
publish = "public"
command = "./deploy.sh"

[context.production.environment]
HUGO_VERSION = "0.56.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "./deploy-preview.sh"

[context.deploy-preview.environment]
HUGO_VERSION = "0.56.1"
HUGO_ENV = "production"
